name: Publish to RubyGems.org

on:
  workflow_dispatch:

jobs:
  publish:
    name: Build + Publish GPR / RubyGems
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    - name: Build
      run: |
        gem build *.gemspec
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
    - name: Find and tag version
      run: |
        git config --global user.email "bot@wendbaar.nl"
        git config --global user.name "Leon BerenBot"
        TAGNAME=v$(bundle exec rake version)
        git tag -a ${TAGNAME} -m "Tagged w/ Github Action"
        git push origin ${TAGNAME}

    - name: Publish to GPR
      run: |
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}

    - name: Publish to RubyGems
      run: |
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
